# Generated by Django 4.1.3 on 2022-12-06 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_collection',
            name='appearance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products_collection',
            name='aroma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products_collection',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='products_collection',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products_collection',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products_collection',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products_collection',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api_app.products_collection')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
