# Generated by Django 4.1.3 on 2023-02-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_products_collection_appearance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_collection',
            name='user',
        ),
        migrations.AlterField(
            model_name='products_collection',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
