# Generated by Django 4.1.3 on 2023-02-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_products_collection_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_collection',
            old_name='weight',
            new_name='weight_in_gm',
        ),
    ]
