# Generated by Django 4.1.3 on 2023-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_cart_remove_carts_user_carts_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
