# Generated by Django 4.1.3 on 2023-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_collection',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(default='admin', max_length=100, unique=True),
        ),
    ]
