# Generated by Django 4.1.3 on 2023-02-24 06:22

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_products_collection_quantity_alter_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_collection',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.CharField(max_length=100), unique=True),
        ),
    ]
